name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Setup Java
      uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
      with:
        distribution: temurin
        java-version: 25
    - name: Downgrade to Kotlin 2.3
      env:
        GH_TOKEN: ${{ github.token }}
        KOTLIN_VERSION: 2.3.21
      run: |
        kotlin -version
        gh release download v$KOTLIN_VERSION --repo JetBrains/kotlin --pattern kotlin-compiler-$KOTLIN_VERSION.zip
        unzip -q kotlin-compiler-$KOTLIN_VERSION.zip -d "$RUNNER_TEMP/kotlin"
        echo "$RUNNER_TEMP/kotlin/kotlinc/bin" >> "$GITHUB_PATH"
    - name: Run Help
      run: |
        kotlin -version
        for i in *.main.kts; do ./$i --help; done
